#!/usr/bin/env bash
# ============================================================
#  TC_Tool — Local Installer
#  Usage: bash install.sh
# ============================================================

set -e

APP_NAME="tc_tool"
INSTALL_DIR="${HOME}/.local/share/${APP_NAME}"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/tc-tool"
MIN_PYTHON_MINOR=11   # Python 3.11+

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
ok()   { echo -e "${GREEN}✔${RESET}  $*"; }
info() { echo -e "${CYAN}→${RESET}  $*"; }
warn() { echo -e "${YELLOW}!${RESET}  $*"; }
die()  { echo -e "${RED}✘  ERROR: $*${RESET}" >&2; exit 1; }

echo -e "${BOLD}============================================${RESET}"
echo -e "${BOLD}   SE Oil & Gas Autoforecasting Tool        ${RESET}"
echo -e "${BOLD}   Local Installer                          ${RESET}"
echo -e "${BOLD}============================================${RESET}"
echo

# ── 1. Find Python 3.11+ ────────────────────────────────────
info "Checking Python version..."
PYTHON=""
for cmd in python3.12 python3.11 python3 python; do
    if command -v "$cmd" &>/dev/null; then
        ver=$("$cmd" -c "import sys; print(sys.version_info.minor)" 2>/dev/null)
        maj=$("$cmd" -c "import sys; print(sys.version_info.major)" 2>/dev/null)
        if [[ "$maj" -eq 3 && "$ver" -ge "$MIN_PYTHON_MINOR" ]]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

[[ -z "$PYTHON" ]] && die "Python 3.${MIN_PYTHON_MINOR}+ not found. Please install it and re-run."
PYVER=$("$PYTHON" --version)
ok "Found $PYVER  ($PYTHON)"

# ── 2. Determine source directory ───────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
info "Source directory: $SCRIPT_DIR"

# ── 3. Create install directory ─────────────────────────────
info "Installing to: $INSTALL_DIR"
if [[ -d "$INSTALL_DIR" ]]; then
    warn "Existing installation found. It will be updated."
fi
mkdir -p "$INSTALL_DIR"

# ── 4. Copy application files ───────────────────────────────
info "Copying application files..."
cp -r "$SCRIPT_DIR/app.py"               "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR/core.py"              "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR/requirements.txt"     "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR/__init__.py"          "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR/generate_tc_pptx.js" "$INSTALL_DIR/"
cp -r "$SCRIPT_DIR/package.json"         "$INSTALL_DIR/"
[[ -f "$SCRIPT_DIR/package-lock.json" ]] && cp "$SCRIPT_DIR/package-lock.json" "$INSTALL_DIR/"
mkdir -p "$INSTALL_DIR/static"
[[ -f "$SCRIPT_DIR/static/logo.png" ]] && cp "$SCRIPT_DIR/static/logo.png" "$INSTALL_DIR/static/"
ok "Files copied."

# ── 5. Create virtual environment ───────────────────────────
VENV_DIR="${INSTALL_DIR}/.venv"
if [[ -d "$VENV_DIR" ]]; then
    info "Reusing existing virtual environment..."
else
    info "Creating virtual environment..."
    "$PYTHON" -m venv "$VENV_DIR"
    ok "Virtual environment created."
fi

VENV_PYTHON="${VENV_DIR}/bin/python"
VENV_PIP="${VENV_DIR}/bin/pip"

# ── 6. Install Python dependencies ──────────────────────────
info "Installing Python dependencies (this may take a minute)..."
"$VENV_PIP" install --quiet --upgrade pip
"$VENV_PIP" install --quiet -r "${INSTALL_DIR}/requirements.txt"
ok "Python dependencies installed."

# ── 6b. Install Node.js dependencies (PPTX export) ──────────
if command -v npm &>/dev/null; then
    info "Installing Node.js dependencies for PPTX export..."
    npm install --prefix "$INSTALL_DIR" --silent
    ok "Node.js dependencies installed."
else
    warn "npm not found — PPTX export will be unavailable. Install Node.js to enable it."
fi

# ── 7. Create launcher script ───────────────────────────────
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# TC_Tool launcher — generated by install.sh
exec "${VENV_DIR}/bin/streamlit" run "${INSTALL_DIR}/app.py" \\
    --server.enableCORS false \\
    --server.enableXsrfProtection false \\
    "\$@"
EOF
chmod +x "$LAUNCHER"
ok "Launcher created at: $LAUNCHER"

# ── 8. Ensure ~/.local/bin is on PATH ───────────────────────
SHELL_RC=""
case "$SHELL" in
    */bash) SHELL_RC="${HOME}/.bashrc" ;;
    */zsh)  SHELL_RC="${HOME}/.zshrc"  ;;
esac

if [[ -n "$SHELL_RC" ]] && ! grep -q 'export PATH.*\.local/bin' "$SHELL_RC" 2>/dev/null; then
    echo '' >> "$SHELL_RC"
    echo '# Added by TC_Tool installer' >> "$SHELL_RC"
    echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> "$SHELL_RC"
    warn "Added ~/.local/bin to PATH in $SHELL_RC"
    warn "Run: source $SHELL_RC  (or open a new terminal)"
fi

# ── Done ────────────────────────────────────────────────────
echo
echo -e "${GREEN}${BOLD}Installation complete!${RESET}"
echo
echo -e "  Run the tool with:  ${BOLD}tc-tool${RESET}"
echo -e "  Or directly with:   ${BOLD}${LAUNCHER}${RESET}"
echo
echo -e "  The app will open in your browser at ${CYAN}http://localhost:8501${RESET}"
echo
